import "@/styles/index.css";
import { getLocale } from "next-intl/server";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Movieflix",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode,
}>) {

    const locale = await getLocale();

    return (
        <html lang={locale}>
            <body>
                {children}
            </body>
        </html>
    );
}
