import { Header } from "@/components/Header";
import { routing } from "@/i18n/routing";
import { Locale } from "@/i18n/types";
import "@/styles/index.css";
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";

export const metadata: Metadata = {
	title: "Movieflix",
	description: "Generated by create next app",
};

export default async function RootLayout({
	modal,
	children,
	params,
}: Readonly<{
	modal: React.ReactNode,
	children: React.ReactNode,
	params: Promise<{ locale: Locale }>,
}>) {

	const { locale } = await params;

	if (!routing.locales.includes(locale)) {
		notFound();
	}

	const messages = await getMessages();

	return (
		<html lang={locale}>
			<body>
				<NextIntlClientProvider messages={messages}>
					<Header />
					{modal}
					{children}
				</NextIntlClientProvider>
			</body>
		</html>
	);
}
